export const CATEGORIES = [
  { id: "study", label: "Study", iconName: "BookOpen", backendValues: ["Academic", "Library"] },
  { id: "hostels", label: "Hostels", iconName: "BedDouble", backendValues: ["Hostel"] },
  { id: "food", label: "Food", iconName: "UtensilsCrossed", backendValues: ["Food"] },
  { id: "sports", label: "Sports", iconName: "Dumbbell", backendValues: ["Sports"] },
  { id: "medical", label: "Medical", iconName: "Stethoscope", backendValues: ["Medical"] },
  { id: "transport", label: "Transport", iconName: "Bus", backendValues: ["Transport"] },
  { id: "admin", label: "Administration", iconName: "Landmark", backendValues: ["Administration"] }
];

export const LOCATIONS = [
  {
    _id: "1",
    name: "Sports Complex",
    slug: "sports-complex",
    category: "Sports",
    categoryLabel: "Sports",
    building: "SC Block",
    floor: "Ground - 2",
    roomNumber: "Indoor Arena",
    description: "Indoor courts for badminton, table tennis and squash. Outdoor grounds for cricket, football and athletics.",
    openingHours: { open: "6:00 AM", close: "9:00 PM" },
    x: 58,
    y: 50,
    images: ["https://images.unsplash.com/photo-1546519638-68e109498ffc?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=100&auto=format&fit=crop&q=80",
    phone: "+91 11 2784 9462",
    website: "https://dtu.ac.in/sports",
    popular: true
  },
  {
    _id: "2",
    name: "Central Library",
    slug: "central-library",
    category: "Library",
    categoryLabel: "Study",
    building: "Library Block",
    floor: "1st - 3rd Floor",
    roomNumber: "Main Hall",
    description: "Main library with three floors of reading space, digital library access, reference section, and vast academic catalog.",
    openingHours: { open: "9:00 AM", close: "10:00 PM" },
    x: 48,
    y: 42,
    images: ["https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=100&auto=format&fit=crop&q=80",
    phone: "+91 11 2784 9475",
    website: "https://library.dtu.ac.in",
    popular: true
  },
  {
    _id: "3",
    name: "Mech Canteen",
    slug: "mech-canteen",
    category: "Food",
    categoryLabel: "Food",
    building: "Mechanical Block",
    floor: "Ground",
    roomNumber: "Canteen Area",
    description: "Popular student dining spot offering quick snacks, meals, tea, and coffee in a vibrant campus social hub.",
    openingHours: { open: "8:00 AM", close: "8:00 PM" },
    x: 52,
    y: 53,
    images: ["https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=100&auto=format&fit=crop&q=80",
    phone: "",
    website: "",
    popular: false
  },
  {
    _id: "4",
    name: "Vishwakarma Hostel",
    slug: "vishwakarma-hostel",
    category: "Hostel",
    categoryLabel: "Hostels",
    building: "Hostel Block A",
    floor: "Ground - 4th Floor",
    roomNumber: "Rooms 1-120",
    description: "Spacious residential hostel housing undergraduate students with study rooms, a mess, and recreation facilities.",
    openingHours: { open: "Open 24 Hours", close: "" },
    x: 78,
    y: 33,
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=100&auto=format&fit=crop&q=80",
    phone: "+91 11 2784 9283",
    website: "",
    popular: false
  },
  {
    _id: "5",
    name: "Arogya Dham (Medical Centre)",
    slug: "arogya-dham",
    category: "Medical",
    categoryLabel: "Medical",
    building: "Health Centre",
    floor: "Ground",
    roomNumber: "OPD 1 & 2",
    description: "DTU's primary health centre offering medical assistance, first aid, routine checkups, and 24/7 emergency response support.",
    openingHours: { open: "9:00 AM", close: "5:00 PM" },
    x: 33,
    y: 52,
    images: ["https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=100&auto=format&fit=crop&q=80",
    phone: "+91 11 2784 9400",
    website: "",
    popular: false
  },
  {
    _id: "6",
    name: "Administration Office",
    slug: "administration-office",
    category: "Administration",
    categoryLabel: "Admin",
    building: "Admin Block",
    floor: "1st & 2nd Floor",
    roomNumber: "VC Cabin & Office",
    description: "The administrative core hosting offices for student services, registration, academic affairs, accounts, and leadership.",
    openingHours: { open: "9:30 AM", close: "5:30 PM" },
    x: 52,
    y: 62,
    images: ["https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?w=100&auto=format&fit=crop&q=80",
    phone: "+91 11 2784 9460",
    website: "https://dtu.ac.in",
    popular: true
  },
  {
    _id: "7",
    name: "SPS Cafeteria",
    slug: "sps-cafeteria",
    category: "Food",
    categoryLabel: "Food",
    building: "SPS Block",
    floor: "Ground",
    roomNumber: "Cafeteria",
    description: "Modern cafeteria offering multi-cuisine fast food, fresh juices, shakes, and tea/coffee, extremely popular during class breaks.",
    openingHours: { open: "8:00 AM", close: "9:00 PM" },
    x: 23,
    y: 63,
    images: ["https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=100&auto=format&fit=crop&q=80",
    phone: "",
    website: "",
    popular: false
  },
  {
    _id: "8",
    name: "DTU Main Entrance Gate",
    slug: "main-gate",
    category: "Transport",
    categoryLabel: "Transport",
    building: "Entry Plaza",
    floor: "Outdoors",
    roomNumber: "Main Gate",
    description: "Central entry and exit point of DTU campus, serving as transit pick-up/drop-off for buses, auto-rickshaws, and e-rickshaws.",
    openingHours: { open: "Open 24 Hours", close: "" },
    x: 69,
    y: 68,
    images: ["https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80"],
    thumbnail: "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=100&auto=format&fit=crop&q=80",
    phone: "",
    website: "",
    popular: true
  }
];
